on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Publish Rust Release Asset

jobs:
  publish:
    name: Cargo Publish
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: cargo publish --verbose
      - uses: Swatinem/rust-cache@v1

env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
